Imports Microsoft.VisualBasic
Imports System
Imports System.Windows.Forms

Namespace XtraPivotGrid_ChartsIntegration
	Partial Public Class Form1
		Inherits Form
		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			' Fill the SqlDataSource asynchronously
			SqlDataSource1.FillAsync()
		End Sub
		Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs) Handles MyBase.Load
			' Sets the PivotGridControl as a data source for the ChartControl.
			chartControl1.DataSource = pivotGridControl1
		End Sub
	End Class
End Namespace
